// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/http;

# Hand-authored OpenAPI 3.0 contract for Oracle Fusion Cloud's "erpintegrations" REST resource, used to upload FBDI files to WebCenter Content (UCM) and submit/monitor the ESS jobs that import them (uploadFileToUCM, importBulkData, submitESSJobRequest, getESSJobStatus).
# 
# There is deliberately no `servers` entry. The base URL is entirely instance-specific - https://{fusionHost}/fscmRestApi/resources/{apiVersion}, e.g. https://acme.fa.us2.oraclecloud.com/fscmRestApi/resources/11.13.18.05 - and any default would be a non-working placeholder. Callers must supply the full base URL.
# 
# Oracle does not publish a machine-readable spec for this API - this document was reconstructed from Oracle's public REST API reference documentation (docs.oracle.com .../farfa/api-erp-processes.html and .../fasop/erp-integrations-rest-service.html) and known sample payloads. Field names/requiredness should be verified against the target Fusion instance's actual release before this is used to generate a production connector.
public isolated client class Client {
    final http:Client clientEp;
    # Gets invoked to initialize the `connector`.
    #
    # + config - The configurations to be used when initializing the `connector` 
    # + serviceUrl - URL of the target service 
    # + return - An error if connector initialization failed 
    public isolated function init(ConnectionConfig config, string serviceUrl) returns error? {
        http:ClientConfiguration httpClientConfig = {auth: config.auth, httpVersion: config.httpVersion, timeout: config.timeout, forwarded: config.forwarded, poolConfig: config.poolConfig, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, validation: config.validation};
        do {
            if config.http1Settings is ClientHttp1Settings {
                ClientHttp1Settings settings = check config.http1Settings.ensureType(ClientHttp1Settings);
                httpClientConfig.http1Settings = {...settings};
            }
            if config.http2Settings is http:ClientHttp2Settings {
                httpClientConfig.http2Settings = check config.http2Settings.ensureType(http:ClientHttp2Settings);
            }
            if config.cache is http:CacheConfig {
                httpClientConfig.cache = check config.cache.ensureType(http:CacheConfig);
            }
            if config.responseLimits is http:ResponseLimitConfigs {
                httpClientConfig.responseLimits = check config.responseLimits.ensureType(http:ResponseLimitConfigs);
            }
            if config.secureSocket is http:ClientSecureSocket {
                httpClientConfig.secureSocket = check config.secureSocket.ensureType(http:ClientSecureSocket);
            }
            if config.proxy is http:ProxyConfig {
                httpClientConfig.proxy = check config.proxy.ensureType(http:ProxyConfig);
            }
        }
        http:Client httpEp = check new (serviceUrl, httpClientConfig);
        self.clientEp = httpEp;
        return;
    }

    # Get ESS job status via finder
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Job status result 
    remote isolated function getESSJobStatus(map<string|string[]> headers = {}, *GetESSJobStatusQueries queries) returns ESSJobStatusResponse|error {
        string resourcePath = string `/erpintegrations`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Invoke an ERP Integrations operation (upload, import, or submit)
    #
    # + headers - Headers to be sent with the request 
    # + payload - The operation request. The concrete shape is selected by the OperationName field: uploadFileToUCM, importBulkData, or submitESSJobRequest. 
    # + return - Operation result 
    remote isolated function invokeErpIntegrationOperation(ErpIntegrationRequest payload, map<string|string[]> headers = {}) returns ErpIntegrationResponse|error {
        string resourcePath = string `/erpintegrations`;
        // Post-generation patch: the record is passed directly so that `http` serialises it with
        // its `@jsondata:Name` wire names (`OperationName`, ...). The generated
        // `payload.toJson()` used `value:toJson`, which ignores the annotations and emitted
        // Ballerina field names (`operationName`, ...) that Oracle Fusion rejects.
        // See docs/spec/sanitations.md - "Post-generation patches".
        return self.clientEp->post(resourcePath, payload, headers);
    }
}
