// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/data.jsondata;
import ballerina/http;

public type ESSJobStatusResponse record {
    int count?;
    boolean hasMore?;
    ESSJobStatusItem[] items?;
};

public type SubmitESSJobRequest record {
    @jsondata:Name {value: "OperationName"}
    "submitESSJobRequest" operationName;
    @jsondata:Name {value: "JobPackageName"}
    string jobPackageName;
    @jsondata:Name {value: "ESSParameters"}
    string essParameters;
    @jsondata:Name {value: "DocumentId"}
    string documentId;
    @jsondata:Name {value: "JobDefName"}
    string jobDefName;
};

# Provides settings related to HTTP/1.x protocol.
public type ClientHttp1Settings record {|
    # Specifies whether to reuse a connection for multiple requests
    http:KeepAlive keepAlive = http:KEEPALIVE_AUTO;
    # The chunking behaviour of the request
    http:Chunking chunking = http:CHUNKING_AUTO;
    # Proxy server related options
    ProxyConfig proxy?;
|};

# Represents the Queries record for the operation: getESSJobStatus
public type GetESSJobStatusQueries record {
    # Use ESSJobStatusRF;requestId={ReqstId} to check the status of a previously submitted request.
    string finder;
};

public type UploadFileToUCMRequest record {
    @jsondata:Name {value: "ContentType"}
    string contentType;
    @jsondata:Name {value: "OperationName"}
    "uploadFileToUCM" operationName;
    @jsondata:Name {value: "DocumentContent"}
    string documentContent;
    @jsondata:Name {value: "DocumentAccount"}
    string documentAccount;
    @jsondata:Name {value: "FileName"}
    string fileName;
    @jsondata:Name {value: "DocumentId"}
    string? documentId?;
};

public type ESSJobStatusItem record {
    @jsondata:Name {value: "OperationName"}
    string operationName?;
    @jsondata:Name {value: "DocumentId"}
    string? documentId?;
    @jsondata:Name {value: "ReqstId"}
    string reqstId?;
    @jsondata:Name {value: "RequestStatus"}
    string requestStatus?;
};

public type ImportBulkDataRequest record {
    @jsondata:Name {value: "CallbackURL"}
    string? callbackURL?;
    @jsondata:Name {value: "NotificationCode"}
    string notificationCode?;
    @jsondata:Name {value: "ContentType"}
    string contentType;
    @jsondata:Name {value: "OperationName"}
    "importBulkData" operationName;
    @jsondata:Name {value: "DocumentContent"}
    string documentContent;
    @jsondata:Name {value: "DocumentAccount"}
    string documentAccount;
    @jsondata:Name {value: "FileName"}
    string fileName;
    @jsondata:Name {value: "JobName"}
    string jobName;
    @jsondata:Name {value: "JobOptions"}
    string jobOptions?;
    @jsondata:Name {value: "ParameterList"}
    string parameterList;
};

# Proxy server configurations to be used with the HTTP client endpoint.
public type ProxyConfig record {|
    # Host name of the proxy server
    string host = "";
    # Proxy server port
    int port = 0;
    # Proxy server username
    string userName = "";
    # Proxy server password
    @display {label: "", kind: "password"}
    string password = "";
|};

public type ErpIntegrationResponse record {
    @jsondata:Name {value: "RqstId"}
    string rqstId?;
    @jsondata:Name {value: "ContentType"}
    string contentType?;
    @jsondata:Name {value: "OperationName"}
    string operationName?;
    @jsondata:Name {value: "DocumentAccount"}
    string documentAccount?;
    @jsondata:Name {value: "FileName"}
    string fileName?;
    @jsondata:Name {value: "DocumentId"}
    string? documentId?;
    @jsondata:Name {value: "JobName"}
    string jobName?;
    @jsondata:Name {value: "ReqstId"}
    string reqstId?;
    @jsondata:Name {value: "RequestStatus"}
    string? requestStatus?;
};

public type ErpIntegrationRequest UploadFileToUCMRequest|ImportBulkDataRequest|SubmitESSJobRequest;

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # Configurations related to client authentication
    http:OAuth2ClientCredentialsGrantConfig|http:CredentialsConfig auth;
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    ClientHttp1Settings http1Settings?;
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings?;
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 60;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache?;
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits?;
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};
