[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "oraclefusion.erp.integrations"
version = "0.1.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Type/Connector", "Vendor/Oracle", "Cost/Paid", "Area/ERP", "Oracle Fusion", "ERP", "FBDI", "ESS", "Finance & Accounting/ERP"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-oraclefusion.erp.integrations"

[build-options]
observabilityIncluded = true
